# Generated by Django 4.2.11 on 2024-05-15 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=1.99)),
                ('old_price', models.IntegerField(default=2.99)),
                ('description', models.CharField(max_length=500)),
                ('specification', models.TextField(max_length=1000)),
                ('publish_date', models.DateField()),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('review_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobno', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details_for_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1.99)),
                ('image', models.ImageField(upload_to='')),
                ('total_item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('order_arrival_date', models.DateField(default=main_app.models.get_future_date)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Billing_details_for_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobno', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product_details_for_order')),
            ],
        ),
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=1.99)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('total_item_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.registration')),
            ],
        ),
    ]
