# Generated by Django 4.2.11 on 2024-05-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
    ]
