# Generated by Django 4.2.11 on 2024-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_mobno_registration_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
